name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MOONWELL_DEPLOY_PK: ${{secrets.MOONWELL_DEPLOY_PK}}

jobs:
  build_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v2
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if the cached directory was not found)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Clean Contracts
        run: npx hardhat clean

      - name: Compile Contracts
        run: npx hardhat compile

      - name: Test Contracts
        run: npx hardhat test
